namespace: prod
replicaCount: 2

image:
  repository: 040235853848.dkr.ecr.ap-south-1.amazonaws.com/devops-app
  tag: prod-9
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  host: goodcampprod.ddns.net

env:
  mongodbUrl: ""

hpa:
  minReplicas: 2
  maxReplicas: 6
  cpuUtilization: 70
