apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: prod
type: Opaque
data:
  mongodb-url: bW9uZ29kYitzcnY6Ly9kZXZvcHNhZG1pbjpEaGlyYWpAMTIzQGRldm9wcy1jbHVzdGVyLnF4MXVydzMubW9uZ29kYi5uZXQvP2FwcE5hbWU9ZGV2b3BzLWNsdXN0ZXI=
