namespace: prod
replicaCount: 3

image:
  repository: 040235853848.dkr.ecr.ap-south-1.amazonaws.com/devops-app
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  host: yourdomain.com

env:
  mongodbUrl: "YOUR_MONGODB_URL"

hpa:
  minReplicas: 3
  maxReplicas: 10
  cpuUtilization: 70
