apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: app
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: mongodb-url
        - name: MAPBOX_TOKEN
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: mapbox-token
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: secret
        - name: CLOUDINARY_CLOUD_NAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: cloudinary-name
        - name: CLOUDINARY_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: cloudinary-key
        - name: CLOUDINARY_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: cloudinary-secret
